/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        color1: "#0A2647",
        color2: "#144272",
        color3: "#205295",
        color4: "#2C74B3",
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: true,
    darkTheme: "emerald",
    // themes: [
    //   "light",
    //   "dark",
    //   "cupcake",
    //   "bumblebee",
    //   "emerald",
    //   "corporate",
    //   "synthwave",
    //   "retro",
    //   "cyberpunk",
    //   "valentine",
    //   "halloween",
    //   "garden",
    //   "forest",
    //   "aqua",
    //   "lofi",
    //   "pastel",
    //   "fantasy",
    //   "wireframe",
    //   "black",
    //   "luxury",
    //   "dracula",
    //   "cmyk",
    //   "autumn",
    //   "business",
    //   "acid",
    //   "lemonade",
    //   "night",
    //   "coffee",
    //   "winter",
    // ],
  },
};
